[package]
name = "dong"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
chrono = "0.4.42"
crossterm = "0.29.0"
lazy_static = "1.5.0"
pulldown-cmark = "0.13.0"
ratatui = "0.29.0"
tokio = { version = "1.47.1", features = ["full"] }
tui-markdown = "0.3.5"
tui-textarea = "0.7.0"
uuid = { version = "1.0", features = ["v4"] }
